version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: smart-house
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./car-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/smart-house
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=123 --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100

#  frontend:
#    build:
#      context: ./smartHome-front
#    ports:
#      - "80:80"
#    depends_on:
#      - backend